USE [master]
GO

/****** Object:  Database [PolyBook]    Script Date: 3/19/2026 8:40:33 AM ******/
CREATE DATABASE [PolyBook]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PolyBook', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.MSSQLSERVER01\MSSQL\DATA\PolyBook.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PolyBook_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.MSSQLSERVER01\MSSQL\DATA\PolyBook_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PolyBook].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PolyBook] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PolyBook] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PolyBook] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PolyBook] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PolyBook] SET ARITHABORT OFF 
GO

ALTER DATABASE [PolyBook] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PolyBook] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PolyBook] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PolyBook] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PolyBook] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PolyBook] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PolyBook] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PolyBook] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PolyBook] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PolyBook] SET  ENABLE_BROKER 
GO

ALTER DATABASE [PolyBook] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PolyBook] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PolyBook] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PolyBook] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PolyBook] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PolyBook] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PolyBook] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PolyBook] SET RECOVERY FULL 
GO

ALTER DATABASE [PolyBook] SET  MULTI_USER 
GO

ALTER DATABASE [PolyBook] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PolyBook] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PolyBook] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PolyBook] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PolyBook] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PolyBook] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [PolyBook] SET OPTIMIZED_LOCKING = OFF 
GO

ALTER DATABASE [PolyBook] SET QUERY_STORE = ON
GO

ALTER DATABASE [PolyBook] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [PolyBook] SET  READ_WRITE 
GO

